server:
    port: 8090
spring:
    application:
        name: third-party-auth
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        deserialization.accept_empty_string_as_null_object: true

    datasource:
        url: jdbc:mysql://192.168.88.100:3306/db-ocean?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&useAffectedRows=true&rewriteBatchedStatements=true
        username: root
        password: F@yuan5015
        driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
    mapper-locations: classpath*:mapper/*Mapper.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
